package com.energy.analysis.repository;

import com.energy.analysis.model.ForecastData; // Forecast data model
import org.springframework.data.jpa.repository.JpaRepository; // Inherited ORM capabilities
import org.springframework.stereotype.Repository; // Application context binding
import java.time.LocalDateTime; // Constraints management
import java.util.List; // Data Array handling

/**
 * Repository interface for managing Forecast predictions generated by WEKA models.
 * Essential for UI chart rendering arrays plotting future generated watts.
 */
@Repository // Injected automatically by Spring context where needed via Autowired structures
public interface ForecastDataRepository extends JpaRepository<ForecastData, Long> {
    
    /**
     * Queries sequential prediction logs produced strictly by a designated model inside a designated timeframe.
     * 
     * @param modelId Source identifier for the machine learning algorithm
     * @param start Slice beginning limits
     * @param end Slice chronological ending restriction 
     * @return Sequential chronologically organized array of point predictions plotting future output
     */
    List<ForecastData> findByForecastModelIdAndDateTimeBetweenOrderByDateTimeAsc(Long modelId, LocalDateTime start, LocalDateTime end);
}
