package com.energy.analysis.model;

import jakarta.persistence.*; // Import JPA annotations
import java.time.LocalDateTime; // Import LocalDateTime

/**
 * Entity representing forecasted power data.
 * This table stores the generated power predictions made by the machine learning models.
 */
@Entity // Marks this class as a persistent JPA entity
@Table(name = "forecast_data") // Defines the name of the mapped table as 'forecast_data'
public class ForecastData {

    @Id // Identifies the primary key of the table
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Uses database auto-increment identity column
    private Long id; // The unique internal ID for each forecast record

    @ManyToOne // Many forecast records can be generated by a single model
    @JoinColumn(name = "model_id", nullable = false) // The foreign key referencing 'forecast_model'
    private ForecastModel forecastModel; // The specific model used to generate this prediction

    @OneToOne // Each forecast record corresponds perfectly to one set of weather inputs
    @JoinColumn(name = "api_weather_id", nullable = false) // Foreign key referencing 'api_weather_data'
    private ApiWeatherData apiWeatherData; // The underlying weather input used to predict this power

    @Column(name = "date_time", nullable = false) // The target date and time for the prediction
    private LocalDateTime dateTime; // The future timestamp for which this prediction is valid

    @Column(name = "predicted_power_kw", nullable = false) // The core output: predicted power
    private Double predictedPowerKw; // The estimated energy generation in Kilowatts

    /**
     * Default constructor required by JPA.
     */
    public ForecastData() {
        // JPA mandates a no-arg constructor
    }

    // --- Getters and Setters ---

    public Long getId() {
        return id; // Retrieve the forecast ID
    }

    public void setId(Long id) {
        this.id = id; // Set the forecast ID
    }

    public ForecastModel getForecastModel() {
        return forecastModel; // Retrieve the associated machine learning model
    }

    public void setForecastModel(ForecastModel forecastModel) {
        this.forecastModel = forecastModel; // Assign the machine learning model
    }

    public ApiWeatherData getApiWeatherData() {
        return apiWeatherData; // Retrieve the input weather parameters
    }

    public void setApiWeatherData(ApiWeatherData apiWeatherData) {
        this.apiWeatherData = apiWeatherData; // Assign the input weather parameters
    }

    public LocalDateTime getDateTime() {
        return dateTime; // Retrieve the target forecast timestamp
    }

    public void setDateTime(LocalDateTime dateTime) {
        this.dateTime = dateTime; // Assign the target forecast timestamp
    }

    public Double getPredictedPowerKw() {
        return predictedPowerKw; // Retrieve the generated output prediction
    }

    public void setPredictedPowerKw(Double predictedPowerKw) {
        this.predictedPowerKw = predictedPowerKw; // Set the output prediction prediction
    }
}
