package com.energy.analysis.service; // Logical grouping context

import com.energy.analysis.model.*; // Object mappings
import com.energy.analysis.repository.*; // Data access
import org.slf4j.Logger; // Log facade
import org.slf4j.LoggerFactory; // Log instantiator
import org.springframework.beans.factory.annotation.Autowired; // Dependency injection
import org.springframework.stereotype.Service; // Bean declaration
import weka.classifiers.functions.LinearRegression; // WEKA Math algorithm
import weka.core.*; // WEKA core objects
import jakarta.annotation.PostConstruct; // Initialization hooks
import java.io.File; // File systems
import java.io.IOException; // File exception handling

import org.springframework.transaction.annotation.Transactional; // Database safety

import java.time.LocalDateTime; // Datetime support
import java.util.ArrayList; // Dynamic Arrays
import java.util.List; // Collections
import java.util.stream.Stream; // Stream logic
import java.util.Map; // Dictionaries
import java.util.HashMap; // Dictionary impl
import java.util.stream.Collectors; // Stream utilities
import java.time.LocalDate; // Day grouping

/**
 * Service to manage energy output predictions using Weka Machine Learning.
 * This class handles training the Linear Regression model and generating
 * future power generation estimates based on incoming weather forecasts.
 */
@Service // Marks this unit as a persistent singleton business component in Spring
public class PredictionService {

    // SLF4J binding used to emit system logs associated with model training phases 
    private static final Logger log = LoggerFactory.getLogger(PredictionService.class);

    // Final references to data repositories protecting against mutability 
    private final SolarPlantRepository plantRepo; // Plant access
    private final TrainingFeatureRepository trainingFeatureRepo; // Historic training datasets
    private final ApiWeatherDataRepository apiWeatherDataRepo; // Incoming predicted logic
    private final ForecastModelRepository forecastModelRepo; // ML Metadata storage
    private final ForecastDataRepository forecastDataRepo; // Generated forecast outputs
    
    // Internal Weka Machine Learning operational state instances 
    private LinearRegression mlModel; // The active predictive mathematical function generated by Weka 
    private Instances datasetStructure; // Definitions outlining exactly what inputs/outputs the model accepts
    
    // Constant string references indicating where physical '.model' files are cached on disk 
    private static final String MODEL_DIR = "models"; // Target folder
    private static final String MODEL_FILE = MODEL_DIR + "/solar_model.model"; // Full disk path

    /**
     * Dependency-injected constructor providing mockability.
     */
    @Autowired // Auto-wires injection automatically at startup
    public PredictionService(SolarPlantRepository plantRepo,
                             TrainingFeatureRepository trainingFeatureRepo,
                             ApiWeatherDataRepository apiWeatherDataRepo,
                             ForecastModelRepository forecastModelRepo,
                             ForecastDataRepository forecastDataRepo) {
        this.plantRepo = plantRepo; // Assing singleton
        this.trainingFeatureRepo = trainingFeatureRepo; // Assign singleton
        this.apiWeatherDataRepo = apiWeatherDataRepo; // Assign singleton
        this.forecastModelRepo = forecastModelRepo; // Assign singleton
        this.forecastDataRepo = forecastDataRepo; // Assign singleton
    }

    /**
     * Hook executing immediately after Spring finishes assembling this Bean.
     * Restores previous ML models from the hard drive so they don't have to retrain on every boot.
     */
    @PostConstruct // Directs Spring to trigger this post-wiring  
    public void init() {
        log.info("Initializing PredictionService - Attempting to load existing model...");
        // Execute the internal disk-deserialization procedure
        loadModel(); 
    }

    /**
     * Exposes full repository array of previously forecasted timestamps.
     * @return List of arrays containing forecast objects 
     */
    public List<ForecastData> getLatestPredictions() {
        // Direct passthrough to the underlying DB repository array
        return forecastDataRepo.findAll(); 
    }

    /**
     * Orchestrates the complex math required to evaluate historic data and spit out an ML equation.
     */
    @Transactional // Guarantees database atomicity while iterating over massive datasets securely
    public void trainModel() {
        log.info("Starting Weka model training..."); // Boot signal 

        // Define the exact column schema formatting the model requires to understand its inputs
        ArrayList<Attribute> attributes = new ArrayList<>(); // Allocate empty WEKA properties list
        attributes.add(new Attribute("ambient_temp_c")); // Weka Feature 0: Outside Temp
        attributes.add(new Attribute("irradiation_wm2")); // Weka Feature 1: Sun Intensity
        attributes.add(new Attribute("sum_ac_power_kw")); // Weka Feature 2: Target Power Goal 

        // Constructs a totally blank Weka Instances dataset holding only our attribute schema definitions
        datasetStructure = new Instances("SolarPrediction", attributes, 0); 
        
        // We explicitly command Weka that the LAST attribute (index 2 / sum_ac_power) is the target variable it must learn to predict
        datasetStructure.setClassIndex(datasetStructure.numAttributes() - 1); 

        // We launch a high-performance DB Stream avoiding RAM Out-Of-Memory exceptions caused by fetching 100,000+ rows simultaneously 
        try (Stream<TrainingFeature> featureStream = trainingFeatureRepo.findAllByOrderByDateTimeAsc()) {
            
            // Sequentially evaluate every historic training row pulled by the Stream 
            featureStream.forEach(tf -> { 
                // Initialize a bare double array sized to exactly 3 slots to pack into Weka
                double[] vals = new double[datasetStructure.numAttributes()]; 
                
                // Pack temp safely
                vals[0] = tf.getAmbientTempC() != null ? tf.getAmbientTempC() : 0.0; 
                // Pack sunlight safely
                vals[1] = tf.getIrradiationWm2() != null ? tf.getIrradiationWm2() : 0.0; 
                // Pack historical actual result safely
                vals[2] = tf.getSumAcPowerKw() != null ? tf.getSumAcPowerKw() : 0.0; 

                // Inject the packed dense array directly into Weka's logical dataset architecture structure 
                datasetStructure.add(new DenseInstance(1.0, vals)); 
            });
        } // The AutoCloseable Try block triggers stream shutdown here safely dropping DB lock 

        try {
            // Guard clause blocking math execution on totally uninitialized empty databases 
            if (datasetStructure.numInstances() == 0) {
                log.warn("No training data found in training_features table. Skipping model training.");
                return; // Escape training
            }

            // Instantiate a pristine blank Linear Regression algorithmic engine
            mlModel = new weka.classifiers.functions.LinearRegression(); 
            // Execute the heavy math parsing the massive Dataset structure to derive mathematical constants
            mlModel.buildClassifier(datasetStructure); 
            
            // Confirm the algorithm completion
            log.info("Model trained successfully with {} instances.", datasetStructure.numInstances()); 
            
            // Since we succeeded, serialize the engine state directly to disk so we don't have to repeat this on reboot
            saveModel(); 
            
            // Build a WEKA evaluation suite to determine if our new model is actually accurate mathematically 
            weka.classifiers.Evaluation eval = new weka.classifiers.Evaluation(datasetStructure);
            // Run the algorithm evaluation internally against the dataset metrics
            eval.evaluateModel(mlModel, datasetStructure); 
            
            // Attempt to bind this new mathematically certified model to the primary Solar Plant schema
            SolarPlant plant = plantRepo.findByPlantId("4135001").orElseGet(() -> {
                SolarPlant newPlant = new SolarPlant(); // create shell
                newPlant.setPlantId("4135001"); // init id
                return plantRepo.save(newPlant); // save fallback explicitly
            });
            
            // Check if there's already an 'Active' model node for this facility, or generate a fresh metadata object 
            ForecastModel modelMeta = forecastModelRepo.findBySolarPlantIdAndIsActiveTrue(plant.getId())
                    .orElse(new ForecastModel());
                    
            // Update metadata configurations
            modelMeta.setSolarPlant(plant); // Attach location 
            modelMeta.setModelName("Standard Linear Regression"); // Add human identifier 
            modelMeta.setTrainingDate(LocalDateTime.now()); // Date stamp version trace
            modelMeta.setAccuracyMae(eval.meanAbsoluteError()); // Store mathematical MAE score 
            modelMeta.setAccuracyRmse(eval.rootMeanSquaredError()); // Store mathematical RMSE score
            modelMeta.setActive(true); // Flag currently active
            forecastModelRepo.save(modelMeta); // Commit updated algorithm tracker properties 

        } catch (Exception e) {
            // Failsafe catch guarding against WEKA math failures or SQL constraint locks 
            log.error("Failed to build Weka model", e); 
        }
    }

    /**
     * Serializes Weka engine configurations out to physical HD structures.
     */
    private void saveModel() {
        try {
            File dir = new File(MODEL_DIR); // Prepare logical dir mapping
            if (!dir.exists()) { // Verify presence
                dir.mkdirs(); // Generate directory tree 
            }
            // Ask SerializationHelper nicely to dump the instantiated algorithm byte-for-byte to .model file
            SerializationHelper.write(MODEL_FILE, mlModel); 
            // Crucially also dump the SCHEMA. Weka errors out if a model doesn't understand the shape of future data inputs
            SerializationHelper.write(MODEL_FILE + ".schema", datasetStructure); 
            
            log.info("Model saved successfully to {}", MODEL_FILE); // Log success string
        } catch (Exception e) {
            log.error("Error saving model to file", e); // Print diagnostic output on failure 
        }
    }

    /**
     * Boot-up process de-serializing the Weka binary blobs back into alive Java Ram instances.
     */
    private void loadModel() {
        File file = new File(MODEL_FILE); // Define lookup target
        if (file.exists()) { // Verify presence actively 
            try {
                // Read binary back into regression object 
                mlModel = (weka.classifiers.functions.LinearRegression) SerializationHelper.read(MODEL_FILE); 
                // Read binary back into schema Instances object
                datasetStructure = (Instances) SerializationHelper.read(MODEL_FILE + ".schema"); 
                
                log.info("Model loaded successfully from {}", MODEL_FILE); // Affirm load operation
            } catch (Exception e) {
                log.error("Could not load model from disk", e); // Log byte corruption
            }
        } else {
            log.warn("No pre-existing model found at {}", MODEL_FILE); // Report missing file gracefully 
        }
    }

    /**
     * Engine traversing over future weather data using it to output generated predictions in sequence arrays.
     */
    public List<ForecastData> predictNext15Days() {
        List<ForecastData> results = new ArrayList<>(); // Setup payload return array 
        
        // Grab facility target 
        SolarPlant plant = plantRepo.findByPlantId("4135001").orElse(null);
        if (plant == null) return results; // Hard quit on unconfigured systems

        // Retrieve active tracking model metadata row
        ForecastModel modelMeta = forecastModelRepo.findBySolarPlantIdAndIsActiveTrue(plant.getId()).orElse(null);

        // Fail-safe logic: If WEKA models are wiped, or Metadata is wiped, force a sync-retraining event! 
        if (mlModel == null || datasetStructure == null || modelMeta == null || modelMeta.getAccuracyMae() == null) {
            log.warn("Model or metadata missing (desync). Retraining model..."); 
            trainModel(); // Initiate heavy mathematics
            
            if (mlModel == null) return results; // Total failure check 
            
            // We just trained. So grab the brand new active model tracking properties. 
            modelMeta = forecastModelRepo.findBySolarPlantIdAndIsActiveTrue(plant.getId()).orElse(null);
            if (modelMeta == null) return results; // Failsafe missing metadata check 
        }

        LocalDateTime now = LocalDateTime.now(); // Base timezone timeline anchor
        
        // Query database asking for ALL external Web-API provided weather rows pointing 15 days out
        List<ApiWeatherData> forecasts = apiWeatherDataRepo.findBySolarPlantIdAndDateTimeBetweenOrderByDateTimeAsc(
                plant.getId(), now, now.plusDays(15)
        );

        // Sequentially execute prediction matrix logic targeting every returned future hour row
        for (ApiWeatherData forecast : forecasts) { 
            try {
                // We do an Upsert strategy. Fetch exactly matching time-sliced output row, or init a pristine blank row
                ForecastData result = forecastDataRepo.findByForecastModelIdAndDateTimeBetweenOrderByDateTimeAsc(
                        modelMeta.getId(), forecast.getDateTime().minusMinutes(1), forecast.getDateTime().plusMinutes(1))
                        .stream().findFirst().orElse(new ForecastData());
                
                // Tie outputs strictly to the algorithm metadata used 
                result.setForecastModel(modelMeta); 
                // Synchronize output generated timestamp directly with future input weather clock timestamp 
                result.setDateTime(forecast.getDateTime()); 
                // Map the weather object physically allowing future traceability identifying WHY the algorithm produced output X
                result.setApiWeatherData(forecast); 

                // Generate a blank WEKA inference row container (Array size 3) 
                weka.core.Instance instance = new weka.core.DenseInstance(3); 
                // Crucially tie the row format explicitly forcing it to respect our defined datasetStructure columns 
                instance.setDataset(datasetStructure); 
                
                // Populate column 0 (Temp)
                instance.setValue(0, forecast.getTempC() != null ? forecast.getTempC() : 0.0); 
                
                // Grab illumination reading natively 
                double rawRadiation = forecast.getIrradiationWm2() != null ? forecast.getIrradiationWm2() : 0.0;
                // Populate column 1 (Radiation)
                instance.setValue(1, rawRadiation); 
                
                // Crucial step! explicitly command WEKA to hide column 2 (Power). This marks it as the "Unknown target" to solve for!
                instance.setMissing(2);

                // Command the Regression algorithm math block to evaluate our "instance" evaluating against its derived formula 
                double predictedPowerWatts = mlModel.classifyInstance(instance);
                
                // The training dataset values were in kilowatts inherently! 
                // WAIT previously the code did Watts -> kW conversion via `/ 1000`. We mirror standard convention protecting outputs 
                double predictedPowerKw = Math.max(0.0, predictedPowerWatts / 1000.0);
                
                // Hardware reality guard clause: True nightfall (Radiation < 10) guarantees Zero generation 
                if (rawRadiation < 10.0) { 
                    predictedPowerKw = 0.0; // Enforce zeroing preventing algorithmic ghost-power outputs 
                }

                // Register successfully validated mathematical generation output 
                result.setPredictedPowerKw(predictedPowerKw); 
                
                // Push physical change back up to database row
                forecastDataRepo.save(result); 
                // Stack response packet array list 
                results.add(result); 

            } catch (Exception e) {
                // If the math breaks down on a dirty datapoint, gracefully bypass leaving rest intact 
                log.error("Prediction failed for date time {}", forecast.getDateTime(), e); 
            }
        }

        // Output completely compiled forecast 
        return results; 
    }
    
    /**
     * Collapses independent weather rows and output rows natively joining them into flat maps for Chart.js frontends.
     */
    public List<Map<String, Object>> getCombinedForecast(int hours) {
        LocalDateTime now = LocalDateTime.now(); // Clock
        LocalDateTime end = now.plusHours(hours); // Calculated constraint limit 
        
        // Find plant origin 
        SolarPlant plant = plantRepo.findByPlantId("4135001").orElse(null);
        if (plant == null) return new ArrayList<>(); // Quick exit 

        // Scan future UI rendering target hours 
        List<ApiWeatherData> weather = apiWeatherDataRepo.findBySolarPlantIdAndDateTimeBetweenOrderByDateTimeAsc(plant.getId(), now, end);
        
        // Locate associated algorithm 
        ForecastModel modelMeta = forecastModelRepo.findBySolarPlantIdAndIsActiveTrue(plant.getId()).orElse(null);
        
        // Fetch raw generated outputs, bypassing via ternary if zero algorithms exist preventing nullpointers
        List<ForecastData> predictions = (modelMeta != null) ? 
                forecastDataRepo.findByForecastModelIdAndDateTimeBetweenOrderByDateTimeAsc(modelMeta.getId(), now, end) : 
                new ArrayList<>();
        
        // Initialize dynamic list containing flat dict maps
        List<Map<String, Object>> combined = new ArrayList<>();
        for (ApiWeatherData w : weather) {
            Map<String, Object> entry = new HashMap<>(); // Standard mapping format 
            // Placed clock timestamp object intact explicitly for Thymeleaf #temporals parsing 
            entry.put("time", w.getDateTime()); 
            entry.put("temp", w.getTempC()); // Insert weather variables
            entry.put("radiation", w.getIrradiationWm2()); // Insert environment vectors
            
            // Execute Stream matching algorithm seeking matching predictions for THIS exact timestamp 
            double power = predictions.stream()
                    .filter(p -> p.getDateTime().isEqual(w.getDateTime())) // Map precise datetime matches
                    .mapToDouble(ForecastData::getPredictedPowerKw) // Strip object down to raw double 
                    .findFirst().orElse(0.0); // If out of sync, default to 0.0
            entry.put("power", power); // Enqueue the final combined matching output 
            
            combined.add(entry); // Push item layout
        }
        return combined; // Supply rendering engine formatted object block
    }

    /**
     * Groups explicitly massive hourly ranges out 15 consecutive days summing up daily expected totals.
     */
    public List<Map<String, Object>> getDailyTotals15d() {
        LocalDateTime now = LocalDateTime.now(); // Anchor clock
        LocalDateTime end = now.plusDays(15); // End restriction 
        
        SolarPlant plant = plantRepo.findByPlantId("4135001").orElse(null); // Node reference 
        if (plant == null) return new ArrayList<>(); // Failsafe empty array

        ForecastModel modelMeta = forecastModelRepo.findBySolarPlantIdAndIsActiveTrue(plant.getId()).orElse(null); // Algorithm fetch
        if (modelMeta == null) return new ArrayList<>(); // Safe escape

        // Blast huge SQL grabbing all chronological occurrences over massive span for this model
        List<ForecastData> all = forecastDataRepo.findByForecastModelIdAndDateTimeBetweenOrderByDateTimeAsc(modelMeta.getId(), now, end);
        
        // Sophisticated Stream executing advanced Grouping operation 
        Map<LocalDate, Double> dailyMap = all.stream()
                .collect(Collectors.groupingBy(
                        p -> p.getDateTime().toLocalDate(), // Key maps values down matching solely on extracted physical calendar DAY
                        Collectors.summingDouble(ForecastData::getPredictedPowerKw) // Execute cumulative summations reducing everything locally 
                ));
        
        // Repackage mapped structure format arrays 
        return dailyMap.entrySet().stream()
                .sorted(Map.Entry.comparingByKey()) // Standard chronological sort execution 
                .map(e -> {
                    Map<String, Object> m = new HashMap<>(); // Hash definition
                    m.put("date", e.getKey().toString()); // Insert Day string hash
                    m.put("yield", e.getValue()); // Populate numerical count
                    return m; // Dump generated obj target 
                }).collect(Collectors.toList()); // Yield assembled target output list structure 
    }
}
